### ISSUE TITLE
TypeScript migration is incompatible with older versions of nodejs

### ISSUE THREAD

**Issue by Supereg** [wollardj/simple-plist#59]
While not stated explicitly, but derived from mentions like in the [1.1.0](https://github.com/wollardj/simple-plist/releases/tag/1.1.0) release notes, the lowest supported node version is assumed to be v10.
However, this project uses v16 for its `@types/node` dependencies, and uses types which aren't present in node v10.
Specifically the type `PathOrFileDescriptor` is not present in older versions of `@types/node`. Instead node uses `PathLike | number`.

As of now, it results in the following typescript compiler errors when trying to compile with a project which is expected to support node v10:
```
node_modules/simple-plist/dist/parse.d.ts:2:10 - error TS2305: Module '"fs"' has no exported member 'PathOrFileDescriptor'.

2 import { PathOrFileDescriptor } from "fs";
           ~~~~~~~~~~~~~~~~~~~~

node_modules/simple-plist/dist/readFile.d.ts:2:10 - error TS2305: Module '"fs"' has no exported member 'PathOrFileDescriptor'.

2 import { PathOrFileDescriptor } from "fs";
           ~~~~~~~~~~~~~~~~~~~~

node_modules/simple-plist/dist/readFileSync.d.ts:2:10 - error TS2305: Module '"fs"' has no exported member 'PathOrFileDescriptor'.

2 import { PathOrFileDescriptor } from "fs";
           ~~~~~~~~~~~~~~~~~~~~

node_modules/simple-plist/dist/writeBinaryFile.d.ts:2:10 - error TS2305: Module '"fs"' has no exported member 'PathOrFileDescriptor'.

2 import { PathOrFileDescriptor, WriteFileOptions } from "fs";
           ~~~~~~~~~~~~~~~~~~~~

node_modules/simple-plist/dist/writeBinaryFileSync.d.ts:2:10 - error TS2305: Module '"fs"' has no exported member 'PathOrFileDescriptor'.

2 import { PathOrFileDescriptor, WriteFileOptions } from "fs";
           ~~~~~~~~~~~~~~~~~~~~

node_modules/simple-plist/dist/writeFile.d.ts:2:10 - error TS2305: Module '"fs"' has no exported member 'PathOrFileDescriptor'.

2 import { PathOrFileDescriptor, WriteFileOptions } from "fs";
           ~~~~~~~~~~~~~~~~~~~~

node_modules/simple-plist/dist/writeFileSync.d.ts:2:10 - error TS2305: Module '"fs"' has no exported member 'PathOrFileDescriptor'.

2 import { PathOrFileDescriptor, WriteFileOptions } from "fs";
           ~~~~~~~~~~~~~~~~~~~~


Found 7 errors.


```

**Comment by wollardj** [comment]
Apologies if I suggested support for node v10 with the latest releases. As a general rule, I tend to shy away from supporting tools or dependencies that aren't supported by their own creators. For node specifically, I take that one step further and only attempt to support and test on the LTS versions. If you head over to [nodejs.org](https://nodejs.org/en/about/releases/) you can see that even version 12 is nearing its end of life and 14 is already in maintenance mode. I'm including a screenshot of the relevant table here for posterity. 

<img width="759" alt="image" src="https://user-images.githubusercontent.com/2027935/160965460-f6bfb3a7-5f92-44a3-81b9-193195ae11a7.png">

**Comment by Supereg** [comment]
Thanks for the detailed clarification. If I remember correctly, back when this issue was created, node v10 wasn’t yet end of life. So this kind of resolved itself.

Just to have it clearly stated, what are the officially supported node versions as of right now? v12, v14 and v16?
